const TOKEN1_ADDRESS = process.env.TOKEN1_ADDRESS!;
const TOKEN2_ADDRESS = process.env.TOKEN2_ADDRESS!;
const SWAP_ROUTER_ADDRESS = process.env.SWAP_ROUTER_ADDRESS!;
const QUOTE_ADDRESS = process.env.QUOTE_ADDRESS!;
const POSITION_MANAGER_ADDRESS = process.env.POSITION_MANAGER_ADDRESS!;
const FACTORY_ADDRESS = process.env.FACTORY_ADDRESS!;

export {
  TOKEN1_ADDRESS,
  TOKEN2_ADDRESS,
  SWAP_ROUTER_ADDRESS,
  QUOTE_ADDRESS,
  POSITION_MANAGER_ADDRESS,
  FACTORY_ADDRESS,
};
